Packer base
Otus-DevOps-2017-11/Raian13_infra pull request #3
Opened 2017-12-24 14:10 UTC by Raian13

Homework 7 - Packer

2017-12-27 10:49 UTC, vitkhab requested changes
Молодец, что справилась с заданием. Так держать!

Требование к улучшению только одно - поправить тип инстанса в `variables.json.example`. Остальное на свое усмотрение.

Документация минимальна, но достаточна. Как пример расширенной документации предлагаю посмотреть https://goo.gl/me4MEX

2017-12-27 10:49 UTC, vitkhab commented on packer/variables.json.example
> +"mach-type": "g1.small",
Некорректный тип инстанса

2017-12-27 10:49 UTC, vitkhab commented on packer/ubuntu16.json
> +			"image_family": "{{user `img-family`}}",
Если параметризируешь `image_family`, то хорошо бы еще и `image_name` запараметризировать. Чтобы в дальнейшем избежать проблемы когда у тебя десяток образов reddit-base в разных семействах.

2018-01-03 14:13 UTC, Raian13 commented
Поправила по замечаниям.

2018-01-09 14:50 UTC, vitkhab approved these changes
Молодец! Так держать!

2018-01-09 18:50 UTC, merged